# -*- coding: utf-8 -*-
"""Assignment4 day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYQnIXCufrl6cFL1YIr0PvpA53yt4njU
"""

n = int(input("Enter the number"))

for i in range(2,n):
  if (n%i != 0):
    a = 1
  else:
    a = 0
    break

if (a==1):
  print("prime number")
else:
  print("not a prime number")