# -*- coding: utf-8 -*-
"""Assignment day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjFayZa5xwh1TohrzgFQX973ChHYMKNA
"""

a = int(input("first number"))
b = int(input("second number"))
sub1 = a - b
mul1 = a * b
div1 = a / b
print("subraction is", sub1)
print("multiplication", mul1)
print("division", div1)