# -*- coding: utf-8 -*-
"""assignment day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_-31DNaklwYlu0UBLO1FdrYnqFU1aBm
"""

maxticketavailable = int(input("enter participants number"))
participants = []
for temp in range(maxticketavailable):
  st = "Ënter the participant name - "+ str(temp + 1) + " - " 
  name = input(st)
  participants.append(name)

#for generating a random name improting random function
import random
b = random.randint(0,maxticketavailable-1)
print(participants[b])