# -*- coding: utf-8 -*-
"""assigment5 day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8kEGX47DQvH9oQdfHONcQUYcNGLC6ZY
"""

#! pip install pytube
#import the package
from pytube import YouTube

url = input('Enter the URL of the video to be download')
my_video = YouTube(url)

print("Video Title")
#get Video Title
print(my_video.title)

#get all the stream resolution for the 
for stream in my_video.streams:
    print(stream)

a = int(input('Enter the itag number to download with respective resolution '))
stream = my_video.streams.get_by_itag(a)
stream.download()

