# -*- coding: utf-8 -*-
"""assignment day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_-31DNaklwYlu0UBLO1FdrYnqFU1aBm
"""

n = int(input("enter participants number"))
p = []
for i in range(n):
  a = input("enter the name")
  p.append(a)

#for generating a random name improting random function
import random
b = random.randint(0,n-1)
print(p[b])